# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pueblos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PueblosNoticias200',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dstitular', models.TextField(blank=True, max_length=1500, null=True)),
                ('dscuerpo', models.TextField(blank=True, max_length=50000, null=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pueblos.PueblosNoticias')),
            ],
            options={
                'db_table': 'pueblos_noticias_200',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PueblosNoticiasPalabras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100)),
                ('noticia_200', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pueblos.PueblosNoticias200')),
            ],
            options={
                'db_table': 'pueblos_noticias_palabras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PueblosPalabrasElimitar',
            fields=[
                ('palabra', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pueblos_palabras_eliminar',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='pueblosnoticiaspalabras',
            unique_together=set([('noticia_200', 'palabra')]),
        ),
    ]
