# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pueblos', '0002_auto_20160427_1118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PueblosPalabrasElimitar',
            new_name='PueblosPalabrasEliminar',
        ),
    ]
