# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pueblos', '0003_auto_20160521_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pueblosnoticias',
            options={'managed': True},
        ),
    ]
