# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pueblos', '0005_auto_20160614_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='pueblosnoticias200',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
