# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pueblos', '0006_pueblosnoticias200_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pueblosnoticias200',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
