# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pueblos', '0007_auto_20160919_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pueblosnoticias200',
            name='test',
        ),
    ]
