# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pueblos', '0008_remove_pueblosnoticias200_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaCategorizada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobado', models.BooleanField(default=False)),
                ('categorias_previas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorized_labels', to='pueblos.PueblosCategoriasSemandal')),
                ('categorias_sugeridas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_labels', to='pueblos.PueblosCategoriasSemandal')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pueblos.PueblosNoticias')),
            ],
            options={
                'db_table': 'pueblos_noticia_categorizada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PueblosConclusion',
            fields=[
                ('c_id', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('c_word', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'conclusion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PueblosPremise',
            fields=[
                ('p_id', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('p_word', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'premise',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PueblosRule',
            fields=[
                ('r_id', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('support', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'rule',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pueblospremise',
            name='r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pueblos.PueblosRule'),
        ),
        migrations.AddField(
            model_name='pueblosconclusion',
            name='r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pueblos.PueblosRule'),
        ),
    ]
