# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pueblos', '0009_auto_20161016_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiacategorizada',
            name='categorias_previas',
        ),
        migrations.AddField(
            model_name='noticiacategorizada',
            name='categorias_sugeridas_palabra',
            field=models.CharField(default='', max_length=80),
        ),
    ]
