# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pueblos', '0012_remove_pueblosnoticiacategorizada_categorias_sugeridas_palabra'),
    ]

    operations = [
        migrations.CreateModel(
            name='PueblosDiccionarioSintactico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=60, unique=True)),
                ('change_word', models.CharField(default='', max_length=60)),
            ],
            options={
                'db_table': 'pueblos_diccionario_sintactico',
                'managed': True,
            },
        ),
    ]
