# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pueblos', '0013_pueblosdiccionariosintactico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pueblosdiccionariosintactico',
            old_name='change_word',
            new_name='replace_word',
        ),
    ]
