# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pueblos', '0016_pueblosnoticiastest_pueblosnoticiastestcategorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='PueblosTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_notices', models.IntegerField(default=1)),
                ('n_notices_test', models.IntegerField(default=1)),
                ('limit', models.IntegerField(default=10)),
                ('use_syn_dict', models.BooleanField(default=False)),
                ('finish', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pueblos_test_case',
                'managed': True,
            },
        ),
    ]
