# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pueblos', '0017_auto_20170111_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pueblostestcase',
            name='finish',
        ),
        migrations.AddField(
            model_name='pueblostestcase',
            name='state',
            field=models.CharField(blank=True, default='not done', max_length=60),
        ),
    ]
