# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pueblos', '0018_auto_20170111_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='pueblostestcase',
            name='conf_support',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='pueblostestcase',
            name='confidence',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='pueblostestcase',
            name='sup_confidence',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='pueblostestcase',
            name='support',
            field=models.FloatField(default=0.5),
        ),
    ]
