# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pueblos', '0021_pueblosnoticiastestcategorias_regla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pueblosnoticiacategorizada',
            name='comprobado',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
